### ISSUE TITLE
Broken link on page about types

### ISSUE THREAD

**Issue by TheOne04** [anyproto/docs#30]
#### Link: https://doc.anytype.io/d/anytype-basics/types

I found another broken link, I think this might be the last broken link remaining!
But I'm not sure what this link is supposed to point to... 

![image](https://github.com/anyproto/docs/assets/64768475/84bc3608-f818-4f75-bdd1-3ffa8ed81be9)

**Comment by charlotte-chiang** [comment]
Thank you @TheOne04 ! I've adjusted several descriptions in this page and fixed the broken link.
