### ISSUE TITLE
How to activate Local Only mode ? Make it explicit

### ISSUE THREAD

**Issue by MarArMar** [anyproto/docs#43]
#### Link
[> URL of the page / pages on which you found the mistake](https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#local-only-mode)

#### Description
I read the doc and have no idea how to activate local only mode & can 't find it

**Comment by isle9** [comment]
Hey @MarArMar. You can find the instructions on how to change to local-only mode in the next [section](https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#switching-between-networks). We'll try to update it to make it more obvious.

**Comment by filip-anytype** [comment]
Hey @MarArMar. You can find the instructions on how to change to local-only mode in the next [section](https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#switching-between-networks). We'll try to update it to make it more obvious.

**Comment by filip-anytype** [comment]
Hey @MarArMar. We've added step by step instructions just for local only mode [here](https://doc.anytype.io/anytype-docs/data-and-security/self-hosting/local-only). There should now be no confusion on how to switch.
