### ISSUE TITLE
Can you consider clipping plugins or APIs that interface with other tools, as well as adding article directory navigation, and converting outlines into mind maps?

### ISSUE THREAD

**Issue by yangmeilia** [anyproto/docs#44]
#### Link
> URL of the page / pages on which you found the mistake

#### Description
> What are the corrections that should be done

-Can you consider clipping plugins or APIs that interface with other tools, as well as adding article directory navigation, and converting outlines into mind maps?
-
-

**Comment by filip-anytype** [comment]
Please post your feedback about the API in this [thread](https://github.com/anyproto/contributors/discussions/218).
