### ISSUE TITLE
Incorrect Link on "Setting Up Your Vault" page

### ISSUE THREAD

**Issue by ben-crumz** [anyproto/docs#66]
#### Link
> https://doc.anytype.io/anytype-docs/basics/vault-and-key/setting-up-your-profile

#### Description
> The "#import-and-export" link leads to the "Customizing Your Space" page instead of the "Import & Export" page. 
>Current link: https://doc.anytype.io/anytype-docs/basics/space/space-settings#import-and-export
>Link it should be: https://doc.anytype.io/anytype-docs/basics/import-export

-
-
-

**Comment by filip-anytype** [comment]
Thank you, fixed in https://github.com/anyproto/docs/commit/4d53e1488d1577273059f9dfe83e5d8d699fa23d.
